services:
  - type: web
    name: perplexity-clone-backend
    runtime: python
    plan: free
    buildCommand: |
      cd server
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      cd server
      uvicorn main:app --host 0.0.0.0 --port $PORT --ws websockets
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: TAVILY_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 10000
    autoDeploy: false